### ISSUE TITLE
看不懂，有没有针对非编程人员的傻瓜式教程？

### ISSUE THREAD

**Issue by ghost** [LouYu2015/WerewolvesWechatBot#1]
看不懂，有没有针对非编程人员的傻瓜式教程？

**Comment by LouYu2015** [comment]
刚刚用 PyInstaller 打包出了一个免安装版本，也细化了一下安装教程。现在用起来应该方便了。不过我还没有测试免安装版本能不能在其他电脑上正常运行，希望你能给我一些反馈。

**Comment by ghost** [comment]
哥们，我微信：(已去除)，加微信聊吧
